# Generated by Django 5.2.17 on 2026-09-22 13:41

import apps.contracts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_modalidad_por_defecto_venta'),
        ('work_orders', '0026_network_access_point'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Trazo capturado en el movil del tecnico, con fondo transparente.', upload_to=apps.contracts.models.contract_signature_path, verbose_name='Firma del abonado')),
                ('signer_name', models.CharField(help_text='Nombre del abonado tal como estaba registrado al firmar. Se copia y no se enlaza: el papel dice quien firmo ese dia.', max_length=200, verbose_name='Firmante')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de firma')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Capturada por')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='contracts.contract', verbose_name='Contrato')),
                ('work_order', models.ForeignKey(blank=True, help_text='Orden durante la cual se recogió la firma.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_signatures', to='work_orders.workorder', verbose_name='Orden de instalación')),
            ],
            options={
                'verbose_name': 'Firma de contrato',
                'verbose_name_plural': 'Firmas de contrato',
            },
        ),
    ]
