# Generated by Django 5.2.17 on 2026-09-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_firma_del_abonado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsignature',
            name='offset_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Desplazamiento horizontal'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='offset_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Desplazamiento vertical'),
        ),
        migrations.AddField(
            model_name='contractsignature',
            name='width',
            field=models.FloatField(blank=True, help_text='En puntos. Vacío deja el tamaño que el sistema calcula.', null=True, verbose_name='Ancho del trazo'),
        ),
    ]
