# Generated by Django 5.2.17 on 2026-08-13 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código de abonado')),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carné de Extranjería'), ('PASSPORT', 'Pasaporte')], max_length=15, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(db_index=True, max_length=20, verbose_name='Número de documento')),
                ('person_type', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('LEGAL', 'Persona Jurídica')], default='NATURAL', max_length=15, verbose_name='Tipo de persona')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Nombres')),
                ('paternal_surname', models.CharField(blank=True, max_length=100, verbose_name='Primer apellido')),
                ('maternal_surname', models.CharField(blank=True, max_length=100, verbose_name='Segundo apellido')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='Razón social / Nombre comercial')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono principal')),
                ('secondary_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono secundario')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='organization.branch', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['paternal_surname', 'maternal_surname', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('reference', models.CharField(blank=True, max_length=300, verbose_name='Referencia')),
                ('district', models.CharField(max_length=120, verbose_name='Distrito')),
                ('meter_number', models.CharField(blank=True, max_length=50, verbose_name='Número de medidor')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud')),
                ('gps_link', models.URLField(blank=True, max_length=500, verbose_name='Enlace GPS')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Dirección principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer', verbose_name='Cliente')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_addresses', to='organization.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Dirección del cliente',
                'verbose_name_plural': 'Direcciones del cliente',
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('document_type', 'document_number'), name='unique_customer_document'),
        ),
    ]
