# Generated by Django 5.2.17 on 2026-08-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='electrical_supply_code',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                verbose_name='Código de suministro eléctrico',
            ),
        ),
    ]
