# Generated by Django 5.2.17 on 2026-08-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='electrical_supply_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de suministro eléctrico'),
        ),
    ]
