# Generated by Django 5.2.17 on 2026-08-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("ATC", "Atención al Cliente"),
                    ("SALES", "Ventas"),
                    ("NOC", "NOC"),
                    ("TECHNICIAN", "Técnico"),
                    ("WAREHOUSE", "Almacén"),
                    ("SUPERVISOR", "Supervisor"),
                    ("RETENTION", "Retenciones"),
                    ("ACCOUNTING", "Contabilidad"),
                ],
                default="ATC",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
