# Generated by Django 5.2.17 on 2026-08-13 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Servicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Plan')),
                ('speed_mbps', models.PositiveIntegerField(blank=True, null=True, verbose_name='Velocidad Mbps')),
                ('technology', models.CharField(blank=True, max_length=50, verbose_name='Tecnología')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio mensual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='services.servicetype', verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['service_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Por instalar'), ('INSTALLATION', 'Instalación'), ('ACTIVE', 'Activo'), ('CUT', 'Cortado'), ('SUSPENDED', 'Suspendido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('service_number', models.PositiveIntegerField(default=1, verbose_name='Número de servicio')),
                ('billing_cycle', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ciclo de facturación')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Fecha de instalación')),
                ('cut_date', models.DateField(blank=True, null=True, verbose_name='Fecha de corte')),
                ('reconnection_date', models.DateField(blank=True, null=True, verbose_name='Fecha de reconexión')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customers.customeraddress', verbose_name='Dirección')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customers.customer', verbose_name='Cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='services.plan', verbose_name='Plan')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='services.servicetype', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['customer', 'service_number'],
            },
        ),
    ]
