# Generated by Django 5.2.17 on 2026-08-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('PRESALE', 'Preventa'), ('INSTALLATION', 'En instalación'), ('ACTIVE', 'Activo'), ('CUT', 'Cortado'), ('SUSPENDED', 'Suspendido'), ('CANCELLED', 'Cancelado')], default='PRESALE', max_length=20, verbose_name='Estado'),
        ),
    ]
