# Generated by Django 5.2.17 on 2026-08-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('services', '0002_alter_subscription_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('customer', 'service_type', 'service_number'), name='unique_customer_service_number'),
        ),
    ]
