# Generated by Django 5.2.17 on 2026-08-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_subscription_unique_customer_service_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='includes_catv',
            field=models.BooleanField(default=False, help_text='Marca si este servicio provee TV por cable.', verbose_name='Incluye CATV'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='includes_internet',
            field=models.BooleanField(default=True, help_text='Marca si este servicio provee conexión a Internet.', verbose_name='Incluye Internet'),
        ),
    ]
