# Generated by Django 5.2.17 on 2026-09-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_plan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialcoveragerule',
            name='commercial_category',
            field=models.CharField(choices=[('TELECABLE', 'Telecable'), ('STANDARD', 'Estándar'), ('PREMIUM', 'Premium'), ('PREMIUM_PLUS', 'Premium Plus'), ('ECONOMIC', 'Económico'), ('SUPER_ECONOMIC', 'Súper económico')], max_length=20, verbose_name='Categoría comercial'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='commercial_category',
            field=models.CharField(blank=True, choices=[('TELECABLE', 'Telecable'), ('STANDARD', 'Estándar'), ('PREMIUM', 'Premium'), ('PREMIUM_PLUS', 'Premium Plus'), ('ECONOMIC', 'Económico'), ('SUPER_ECONOMIC', 'Súper económico')], max_length=20, verbose_name='Categoría comercial'),
        ),
    ]
