# Generated by Django 5.2.17 on 2026-09-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_pronto_pago_dos_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='requires_playhub_account',
            field=models.BooleanField(default=False, help_text='Activar para servicios que se entregan a una cuenta, como APPS. El contrato exigira correo y celular PlayHub.', verbose_name='Requiere cuenta PlayHub'),
        ),
    ]
