# Generated by Django 5.2.17 on 2026-10-02 16:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def confirmed_early_payment(apps, schema_editor):
    policy = apps.get_model('services', 'BillingPolicy')
    policy.objects.filter(code='ANNIVERSARY_PP10').update(
        discount_days_before_due=3, discount_amount=Decimal('10.00'),
    )
    policy.objects.filter(code='CALENDAR_PP5').update(
        discount_deadline_day=29, discount_amount=Decimal('5.00'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_subscription_plan_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingpolicy',
            name='reconnection_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Reconexión tras corte por morosidad'),
        ),
        # Los cargos existentes conservan los importes y fechas de su emisión.
        migrations.RunPython(confirmed_early_payment, migrations.RunPython.noop),
    ]
