# Generated by Django 5.2.17 on 2026-08-13 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de orden')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de orden',
                'verbose_name_plural': 'Tipos de orden',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Motivo')),
                ('classification', models.CharField(blank=True, choices=[('TECHNICAL', 'Técnico'), ('ADMINISTRATIVE', 'Administrativo')], max_length=20, verbose_name='Clasificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasons', to='work_orders.ordertype', verbose_name='Tipo de orden')),
            ],
            options={
                'verbose_name': 'Motivo de orden',
                'verbose_name_plural': 'Motivos de orden',
                'ordering': ['order_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='Número de orden')),
                ('attention_type', models.CharField(choices=[('SYSTEM', 'Sistema / NOC'), ('FIELD', 'Campo')], default='FIELD', max_length=20, verbose_name='Tipo de atención')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('DERIVED', 'Derivada'), ('ATTENDED', 'Atendida'), ('REJECTED', 'Rechazada'), ('NOT_FEASIBLE', 'No factible'), ('CANCELLED', 'Anulada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='NORMAL', max_length=20, verbose_name='Prioridad')),
                ('detail', models.TextField(blank=True, verbose_name='Detalle de la solicitud')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha programada de atención')),
                ('attended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha real de atención')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='organization.branch', verbose_name='Sede')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='work_orders.ordertype', verbose_name='Tipo de orden')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='work_orders.orderreason', verbose_name='Motivo')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='services.subscription', verbose_name='Suscripción')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='organization.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('DERIVED', 'Derivada'), ('ATTENDED', 'Atendida'), ('REJECTED', 'Rechazada'), ('NOT_FEASIBLE', 'No factible'), ('CANCELLED', 'Anulada')], max_length=20, verbose_name='Estado anterior')),
                ('new_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('DERIVED', 'Derivada'), ('ATTENDED', 'Atendida'), ('REJECTED', 'Rechazada'), ('NOT_FEASIBLE', 'No factible'), ('CANCELLED', 'Anulada')], max_length=20, verbose_name='Estado nuevo')),
                ('remarks', models.TextField(blank=True, verbose_name='Observación')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='work_orders.workorder', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='orderreason',
            constraint=models.UniqueConstraint(fields=('order_type', 'code'), name='unique_reason_code_per_order_type'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='wo_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['subscription'], name='wo_subscription_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['created_at'], name='wo_created_at_idx'),
        ),
    ]
