# Generated by Django 5.2.17 on 2026-08-14 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Código')),
                ('name', models.CharField(max_length=120, verbose_name='Subtipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtypes', to='work_orders.ordertype', verbose_name='Tipo de orden')),
            ],
            options={
                'verbose_name': 'Subtipo de orden',
                'verbose_name_plural': 'Subtipos de orden',
                'ordering': ['order_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='work_orders.ordersubtype', verbose_name='Subtipo'),
        ),
        migrations.AddConstraint(
            model_name='ordersubtype',
            constraint=models.UniqueConstraint(fields=('order_type', 'code'), name='unique_subtype_code_per_order_type'),
        ),
    ]
