# Generated by Django 5.2.17 on 2026-08-14 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('work_orders', '0004_orderresult_workorder_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_start_date', models.DateField(blank=True, null=True, verbose_name='Fecha solicitada de inicio')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de retorno')),
                ('cancellation_reason_detail', models.TextField(blank=True, verbose_name='Detalle del motivo')),
                ('competitor', models.CharField(blank=True, max_length=120, verbose_name='Operador al que migra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cut_detail', to='work_orders.workorder', verbose_name='Orden de corte')),
            ],
            options={
                'verbose_name': 'Detalle de corte',
                'verbose_name_plural': 'Detalles de corte',
            },
        ),
        migrations.CreateModel(
            name='TransferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación interna anterior')),
                ('new_location', models.CharField(blank=True, max_length=200, verbose_name='Nueva ubicación interna')),
                ('requires_additional_cabling', models.BooleanField(default=False, verbose_name='Requiere cableado adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_destinations', to='customers.customeraddress', verbose_name='Nueva dirección')),
                ('previous_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_origins', to='customers.customeraddress', verbose_name='Dirección anterior')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_detail', to='work_orders.workorder', verbose_name='Orden de traslado')),
            ],
            options={
                'verbose_name': 'Detalle de traslado',
                'verbose_name_plural': 'Detalles de traslado',
            },
        ),
    ]
