# Generated by Django 5.2.17 on 2026-08-14 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0005_cutdetail_transferdetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio real de atención'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignada'), ('DERIVED', 'Derivada'), ('IN_PROGRESS', 'En atención'), ('ATTENDED', 'Atendida'), ('REPROGRAMMED', 'Reprogramada'), ('REJECTED', 'Rechazada'), ('NOT_FEASIBLE', 'No factible'), ('CANCELLED', 'Anulada')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='workorderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignada'), ('DERIVED', 'Derivada'), ('IN_PROGRESS', 'En atención'), ('ATTENDED', 'Atendida'), ('REPROGRAMMED', 'Reprogramada'), ('REJECTED', 'Rechazada'), ('NOT_FEASIBLE', 'No factible'), ('CANCELLED', 'Anulada')], max_length=20, verbose_name='Estado nuevo'),
        ),
        migrations.AlterField(
            model_name='workorderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignada'), ('DERIVED', 'Derivada'), ('IN_PROGRESS', 'En atención'), ('ATTENDED', 'Atendida'), ('REPROGRAMMED', 'Reprogramada'), ('REJECTED', 'Rechazada'), ('NOT_FEASIBLE', 'No factible'), ('CANCELLED', 'Anulada')], max_length=20, verbose_name='Estado anterior'),
        ),
        migrations.CreateModel(
            name='WorkOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(verbose_name='Fecha de asignación')),
                ('unassigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de desasignación')),
                ('remarks', models.TextField(blank=True, verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='work_orders.workorder', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Asignación de orden',
                'verbose_name_plural': 'Historial de asignaciones',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['work_order'], name='wo_assignment_order_idx'), models.Index(fields=['technician'], name='wo_assignment_tech_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderReprogramming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_schedule', models.DateTimeField(blank=True, null=True, verbose_name='Fecha programada anterior')),
                ('new_schedule', models.DateTimeField(verbose_name='Nueva fecha programada')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo de la reprogramación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order_reprogrammings', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprogrammings', to='work_orders.workorder', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Reprogramación de orden',
                'verbose_name_plural': 'Historial de reprogramaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['work_order'], name='wo_reprog_order_idx')],
            },
        ),
    ]
