# Generated by Django 5.2.17 on 2026-08-15 19:37

import apps.work_orders.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0006_workorder_started_at_alter_workorder_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignada'), ('DERIVED', 'Derivada'), ('IN_PROGRESS', 'En atención'), ('ATTENDED', 'Atendida'), ('LIQUIDATED', 'Liquidada'), ('REPROGRAMMED', 'Reprogramada'), ('REJECTED', 'Rechazada'), ('NOT_FEASIBLE', 'No factible'), ('CANCELLED', 'Anulada')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='workorderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignada'), ('DERIVED', 'Derivada'), ('IN_PROGRESS', 'En atención'), ('ATTENDED', 'Atendida'), ('LIQUIDATED', 'Liquidada'), ('REPROGRAMMED', 'Reprogramada'), ('REJECTED', 'Rechazada'), ('NOT_FEASIBLE', 'No factible'), ('CANCELLED', 'Anulada')], max_length=20, verbose_name='Estado nuevo'),
        ),
        migrations.AlterField(
            model_name='workorderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignada'), ('DERIVED', 'Derivada'), ('IN_PROGRESS', 'En atención'), ('ATTENDED', 'Atendida'), ('LIQUIDATED', 'Liquidada'), ('REPROGRAMMED', 'Reprogramada'), ('REJECTED', 'Rechazada'), ('NOT_FEASIBLE', 'No factible'), ('CANCELLED', 'Anulada')], max_length=20, verbose_name='Estado anterior'),
        ),
        migrations.CreateModel(
            name='WorkOrderLiquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquidated_at', models.DateTimeField(verbose_name='Fecha y hora de liquidación')),
                ('resolution_detail', models.TextField(verbose_name='Detalle de la solución ejecutada')),
                ('technical_notes', models.TextField(blank=True, verbose_name='Observaciones técnicas')),
                ('network_element', models.CharField(blank=True, max_length=120, verbose_name='Elemento de red (NAP / caja / mufa)')),
                ('network_port', models.CharField(blank=True, max_length=30, verbose_name='Puerto')),
                ('equipment_serial', models.CharField(blank=True, max_length=120, verbose_name='Serie del equipo instalado o retirado')),
                ('signal_level_dbm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Nivel de señal (dBm)')),
                ('cable_meters_used', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Metros de cable utilizados')),
                ('krill_reference', models.CharField(blank=True, max_length=60, verbose_name='Referencia Krill (pendiente de integración)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liquidated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_liquidations', to=settings.AUTH_USER_MODEL, verbose_name='Liquidado por')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidation', to='work_orders.workorder', verbose_name='Orden liquidada')),
            ],
            options={
                'verbose_name': 'Liquidación técnica',
                'verbose_name_plural': 'Liquidaciones técnicas',
                'ordering': ['-liquidated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.work_orders.models.evidence_upload_path, verbose_name='Archivo o fotografía')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order_evidences', to=settings.AUTH_USER_MODEL, verbose_name='Adjuntado por')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='work_orders.workorder', verbose_name='Orden')),
                ('liquidation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='work_orders.workorderliquidation', verbose_name='Liquidación')),
            ],
            options={
                'verbose_name': 'Evidencia de atención',
                'verbose_name_plural': 'Evidencias de atención',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderLiquidationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('USED', 'Utilizado'), ('REMOVED', 'Retirado')], default='USED', max_length=20, verbose_name='Tipo de movimiento')),
                ('material_code', models.CharField(blank=True, max_length=40, verbose_name='Código o referencia')),
                ('material_name', models.CharField(max_length=150, verbose_name='Material o equipo')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('unit_of_measure', models.CharField(blank=True, choices=[('UNIT', 'Unidad'), ('METER', 'Metro'), ('ROLL', 'Rollo'), ('SET', 'Juego')], max_length=20, verbose_name='Unidad de medida')),
                ('remarks', models.TextField(blank=True, verbose_name='Observación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liquidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='work_orders.workorderliquidation', verbose_name='Liquidación')),
            ],
            options={
                'verbose_name': 'Material declarado',
                'verbose_name_plural': 'Materiales declarados',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='workorderliquidation',
            index=models.Index(fields=['liquidated_at'], name='wo_liq_date_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderliquidation',
            index=models.Index(fields=['liquidated_by'], name='wo_liq_user_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderevidence',
            index=models.Index(fields=['work_order'], name='wo_evidence_order_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderliquidationitem',
            index=models.Index(fields=['liquidation'], name='wo_liq_item_liq_idx'),
        ),
    ]
