# Generated by Django 5.2.17 on 2026-08-18 13:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0007_alter_workorder_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderLiquidationCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_reason', models.TextField(verbose_name='Motivo indicado por el validador')),
                ('values_before', models.JSONField(blank=True, default=dict, verbose_name='Valores antes de la corrección')),
                ('values_after', models.JSONField(blank=True, default=dict, verbose_name='Valores después de la corrección')),
                ('items_before', models.JSONField(blank=True, default=list, verbose_name='Materiales declarados antes de la corrección')),
                ('items_after', models.JSONField(blank=True, default=list, verbose_name='Materiales declarados después de la corrección')),
                ('remarks', models.TextField(blank=True, verbose_name='Observación del técnico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Corrección de liquidación',
                'verbose_name_plural': 'Correcciones de liquidación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='workorderliquidation',
            options={'ordering': ['-liquidated_at'], 'permissions': [('validate_liquidation', 'Puede validar y solicitar corrección de liquidaciones')], 'verbose_name': 'Liquidación técnica', 'verbose_name_plural': 'Liquidaciones técnicas'},
        ),
        migrations.AddField(
            model_name='workorderliquidation',
            name='correction_count',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)], verbose_name='Correcciones consumidas'),
        ),
        migrations.AddField(
            model_name='workorderliquidation',
            name='correction_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de la corrección solicitada'),
        ),
        migrations.AddField(
            model_name='workorderliquidation',
            name='correction_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de solicitud de corrección'),
        ),
        migrations.AddField(
            model_name='workorderliquidation',
            name='correction_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_liquidation_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Corrección solicitada por'),
        ),
        migrations.AddField(
            model_name='workorderliquidation',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reenvío'),
        ),
        migrations.AddField(
            model_name='workorderliquidation',
            name='review_status',
            field=models.CharField(choices=[('LIQUIDATED', 'Liquidada'), ('SUBMITTED', 'Enviada'), ('CORRECTION_REQUESTED', 'Corrección solicitada'), ('RESUBMITTED', 'Reenviada'), ('VALIDATED', 'Validada')], default='LIQUIDATED', max_length=25, verbose_name='Estado de revisión'),
        ),
        migrations.AddField(
            model_name='workorderliquidation',
            name='submission_remarks',
            field=models.TextField(blank=True, verbose_name='Observación del envío'),
        ),
        migrations.AddField(
            model_name='workorderliquidation',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío'),
        ),
        migrations.AddField(
            model_name='workorderliquidation',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_liquidations', to=settings.AUTH_USER_MODEL, verbose_name='Enviada por'),
        ),
        migrations.AddField(
            model_name='workorderliquidation',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación'),
        ),
        migrations.AddField(
            model_name='workorderliquidation',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_liquidations', to=settings.AUTH_USER_MODEL, verbose_name='Validada por'),
        ),
        migrations.AddField(
            model_name='workorderliquidation',
            name='validation_remarks',
            field=models.TextField(blank=True, verbose_name='Observación de la validación'),
        ),
        migrations.AddIndex(
            model_name='workorderliquidation',
            index=models.Index(fields=['review_status'], name='wo_liq_review_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorderliquidation',
            constraint=models.CheckConstraint(condition=models.Q(('correction_count__lte', 1)), name='wo_liq_correction_count_max_1'),
        ),
        migrations.AddField(
            model_name='workorderliquidationcorrection',
            name='corrected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidation_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Corregida por'),
        ),
        migrations.AddField(
            model_name='workorderliquidationcorrection',
            name='liquidation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='work_orders.workorderliquidation', verbose_name='Liquidación corregida'),
        ),
        migrations.AddIndex(
            model_name='workorderliquidationcorrection',
            index=models.Index(fields=['liquidation'], name='wo_liq_corr_liq_idx'),
        ),
    ]
