# Generated by Django 5.2.17 on 2026-08-20 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0008_workorderliquidationcorrection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreason',
            name='plan_scope',
            field=models.CharField(choices=[('ANY', 'Cualquier plan'), ('CATV', 'Solo CATV (incluye Dúo)'), ('INTERNET', 'Internet o Dúo')], default='ANY', max_length=10, verbose_name='Alcance por plan'),
        ),
        migrations.AddField(
            model_name='orderreason',
            name='subtype',
            field=models.ForeignKey(blank=True, help_text="Opcional. Si se indica, este motivo solo debe ofrecerse cuando la orden tiene este subtipo (por ejemplo, los motivos de un corte 'Definitivo' frente a uno 'Temporal').", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reasons', to='work_orders.ordersubtype', verbose_name='Subtipo'),
        ),
        migrations.AddField(
            model_name='ordersubtype',
            name='plan_scope',
            field=models.CharField(choices=[('ANY', 'Cualquier plan'), ('CATV', 'Solo CATV (incluye Dúo)'), ('INTERNET', 'Internet o Dúo')], default='ANY', max_length=10, verbose_name='Alcance por plan'),
        ),
        migrations.AddField(
            model_name='ordertype',
            name='plan_scope',
            field=models.CharField(choices=[('ANY', 'Cualquier plan'), ('CATV', 'Solo CATV (incluye Dúo)'), ('INTERNET', 'Internet o Dúo')], default='ANY', help_text='Restringe en qué tipo de suscripción (CATV, Internet/Dúo o cualquiera) debe ofrecerse este tipo de orden.', max_length=10, verbose_name='Alcance por plan'),
        ),
    ]
