# Generated by Django 5.2.17 on 2026-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0008_workorderliquidationcorrection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='Año')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Último correlativo emitido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Correlativo de órdenes',
                'verbose_name_plural': 'Correlativos de órdenes',
                'ordering': ['-year'],
            },
        ),
    ]
