# Generated by Django 5.2.17 on 2026-08-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0009_work_order_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at'], 'permissions': [('assign_workorder', 'Puede asignar órdenes de trabajo a un técnico')], 'verbose_name': 'Orden de trabajo', 'verbose_name_plural': 'Órdenes de trabajo'},
        ),
    ]
