# Generated by Django 5.2.17 on 2026-09-02 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_orders", "0011_alter_workorder_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderFieldSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nap",
                    models.CharField(blank=True, max_length=60, verbose_name="NAP"),
                ),
                (
                    "terminal",
                    models.CharField(blank=True, max_length=30, verbose_name="Borne"),
                ),
                (
                    "equipment_code",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="MAC / Equipo"
                    ),
                ),
                (
                    "seal_number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Precinto"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Observaciones del técnico"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_order_field_sheet_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
                (
                    "work_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_sheet",
                        to="work_orders.workorder",
                        verbose_name="Orden de trabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha técnica de campo",
                "verbose_name_plural": "Fichas técnicas de campo",
            },
        ),
    ]
