# Generated by Django 5.2.17 on 2026-09-03 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_orders", "0012_work_order_field_sheet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sold_work_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vendedor",
            ),
        ),
    ]
