# Generated by Django 5.2.17 on 2026-09-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_plan_options'),
        ('work_orders', '0014_seed_tv_annex_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertype',
            name='service_types',
            field=models.ManyToManyField(blank=True, help_text='Servicios sobre los que se puede emitir este tipo de orden. Sin marcar ninguno queda disponible para todos.', related_name='order_types', to='services.servicetype', verbose_name='Servicios que lo ofrecen'),
        ),
    ]
