# Generated by Django 5.2.17 on 2026-09-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0015_ordertype_service_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='attention_type',
            field=models.CharField(choices=[('SYSTEM', 'Sistema'), ('FIELD', 'Física')], default='FIELD', max_length=20, verbose_name='Tipo de atención'),
        ),
    ]
