# Generated by Django 5.2.17 on 2026-09-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0016_alter_workorder_attention_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Se usa cuando el cliente solo comprometió un día de atención, sin hora. Nunca coexiste con scheduled_at: si hay hora pactada, va en scheduled_at y este campo queda vacío.', null=True, verbose_name='Día programado (sin hora)'),
        ),
    ]
