# Generated by Django 5.2.17 on 2026-09-06 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0017_programar_dia_sin_hora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderreprogramming',
            name='new_schedule_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nuevo día programado (sin hora)'),
        ),
        migrations.AddField(
            model_name='workorderreprogramming',
            name='previous_schedule_date',
            field=models.DateField(blank=True, null=True, verbose_name='Día programado anterior (sin hora)'),
        ),
        migrations.AlterField(
            model_name='workorderreprogramming',
            name='new_schedule',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nueva fecha programada'),
        ),
        migrations.AddConstraint(
            model_name='workorderreprogramming',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('new_schedule__isnull', False), ('new_schedule_date__isnull', True)), models.Q(('new_schedule__isnull', True), ('new_schedule_date__isnull', False)), _connector='OR'), name='wo_reprog_exactly_one_new_schedule'),
        ),
    ]
