# Generated by Django 5.2.17 on 2026-09-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0019_schedule_workorder_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at'], 'permissions': [('assign_workorder', 'Puede asignar órdenes de trabajo a un técnico'), ('start_workorder', 'Puede iniciar la atención de órdenes de trabajo'), ('cancel_workorder', 'Puede anular órdenes de trabajo')], 'verbose_name': 'Orden de trabajo', 'verbose_name_plural': 'Órdenes de trabajo'},
        ),
    ]
