# Generated by Django 5.2.17 on 2026-09-09 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0020_alter_workorder_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention_detail', models.TextField(blank=True, verbose_name='Detalle de atención')),
                ('mac', models.CharField(blank=True, max_length=100, verbose_name='MAC / Equipo')),
                ('nap', models.CharField(blank=True, max_length=100, verbose_name='NAP / Caja')),
                ('terminal', models.CharField(blank=True, max_length=50, verbose_name='Borne')),
                ('seal_number', models.CharField(blank=True, max_length=100, verbose_name='Precinto')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attended_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Atendido por')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incident_detail', to='work_orders.workorder', verbose_name='Incidencia')),
            ],
            options={
                'verbose_name': 'Detalle de incidencia',
                'verbose_name_plural': 'Detalles de incidencias',
            },
        ),
    ]
