# Generated by Django 5.2.17 on 2026-09-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0021_incidentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='reason_text',
            field=models.TextField(blank=True, help_text='Motivo escrito por el operador cuando el tipo de orden no utiliza un motivo de catálogo.', verbose_name='Motivo registrado'),
        ),
    ]
