# Generated by Django 5.2.17 on 2026-09-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0023_seed_incident_order_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at'], 'permissions': [('assign_workorder', 'Puede asignar órdenes de trabajo a un técnico'), ('start_workorder', 'Puede iniciar la atención de órdenes de trabajo'), ('cancel_workorder', 'Puede anular órdenes de trabajo'), ('view_incident', 'Puede consultar incidencias NOC'), ('start_incident', 'Puede iniciar la atención de incidencias NOC'), ('close_incident', 'Puede finalizar incidencias NOC')], 'verbose_name': 'Orden de trabajo', 'verbose_name_plural': 'Órdenes de trabajo'},
        ),
    ]
