# Generated by Django 5.2.17 on 2026-09-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0024_alter_workorder_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentdetail',
            name='mac',
        ),
        migrations.RemoveField(
            model_name='incidentdetail',
            name='nap',
        ),
        migrations.RemoveField(
            model_name='incidentdetail',
            name='seal_number',
        ),
        migrations.RemoveField(
            model_name='incidentdetail',
            name='terminal',
        ),
    ]
