# Generated by Django 5.2.17 on 2026-09-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0032_installation_withdrawal'),
        ('work_orders', '0033_seed_fault_results'),
    ]

    operations = [
    ]
