"""Guía sintética versionada: no crea deuda, dinero ni documentos fiscales."""

CATALOG_VERSION = 1


def case(code, title, area, coverage, fields, checks, expected):
    return dict(code=code, title=title, area=area, coverage=coverage,
                fields=fields, checks=checks, expected=expected)


CASES = (
    case("abonado", "01 · Datos del abonado", "Abonados", "Ficha ilustrativa",
         (("Código", "DEMO-CONT-001"), ("Titular", "Persona de Ejemplo QA"),
          ("Documento", "DNI-DEMO (marcador, no es un DNI válido)"),
          ("Dirección del servicio", "Calle de Prueba 100 · distrito y provincia de ejemplo"),
          ("Contacto", "revision@example.invalid"), ("Plan / estado", "Paquete de S/89 · activo")),
         ("¿Se distingue el titular del servicio de quien paga y del receptor del comprobante?",
          "¿Faltan código antiguo, sede, dirección completa, teléfono o correo de entrega?",
          "¿Qué datos deben impedir un alta o quedar pendientes de completar?"),
         "Revisar los campos propuestos. Estos marcadores no se guardan como un abonado real."),
    case("receptor", "02 · Empresa y receptor fiscal", "Facturación", "Por definir con Contabilidad",
         (("Titular del servicio", "Persona de Ejemplo QA"),
          ("Receptor propuesto", "Empresa Ejemplo QA S.A.C."),
          ("RUC receptor / emisor", "RUC-DEMO-RECEPTOR / RUC-DEMO-EMISOR (no válidos)"),
          ("Domicilio fiscal", "Dirección fiscal de ejemplo, distinta de la instalación"),
          ("Documento y condición de pago", "Por confirmar por empresa y operación")),
         ("¿Cuándo factura la empresa emisora y a nombre de quién?",
          "¿Qué datos del receptor se requieren y dónde se conservan?",
          "¿Cómo se identifica el documento solicitado sin confundirlo con el recibo interno?"),
         "Confirmar datos y reglas. No se propone como válida una modalidad tributaria."),
    case("pronto2026", "03 · Mensualidad con pronto pago 2026", "Cobranza", "Muestra operativa disponible",
         (("Precio del paquete", "S/89,00 = servicio S/81,50 + APP S/7,50"),
          ("Descuento comercial", "S/10,00 dentro del plazo"),
          ("Cobro del ejemplo", "S/79,00"), ("Comprobante", "Interno de muestra DEMOQA")),
         ("¿Se ven periodo, fecha límite, descuento, medio de pago y saldo?",
          "¿Cómo debe distribuirse el descuento entre conceptos para la futura emisión?"),
         "S/89,00 − S/10,00 = S/79,00. El reparto tributario del descuento queda por validar."),
    case("normal2026", "04 · Mensualidad fuera del pronto pago", "Cobranza", "Muestra operativa disponible",
         (("Mensualidad", "S/89,00"), ("Descuento", "S/0,00 fuera del plazo"),
          ("Cobro del ejemplo", "S/89,00")),
         ("¿La fecha del pago permite explicar por qué no se aplicó descuento?",
          "¿El saldo y el comprobante coinciden sin añadir una penalidad inexistente?"),
         "El ejemplo cobra S/89,00. No añade intereses ni mora."),
    case("pronto2025", "05 · Política anterior y precio normal", "Cobranza", "Muestras operativas disponibles",
         (("Paquete de referencia", "S/89,00"), ("Dentro del plazo de la política 2025", "S/84,00 con descuento de S/5,00"),
          ("Fuera del plazo", "S/89,00")),
         ("¿Se conserva la política aplicable al periodo histórico?",
          "¿El reporte diferencia ambos casos sin recalcular pagos anteriores con reglas nuevas?"),
         "Comparar los dos comprobantes existentes: S/84,00 y S/89,00."),
    case("proporcional", "06 · Primer mes proporcional", "Cobranza", "Muestra operativa disponible",
         (("Instalación del ejemplo", "Día 7, política calendario"),
          ("Mensualidad completa", "S/89,00"), ("Cargo generado", "S/74,25 antes de descuento")),
         ("¿El periodo de cobertura y la fecha de instalación son comprensibles?",
          "¿Contabilidad acepta la base comercial de 30 días y el redondeo existente?",
          "¿Cómo se diferencia instalación, mensualidad y descuento en el comprobante?"),
         "El importe reproduce la muestra del cálculo actual; el criterio y redondeo requieren revisión."),
    case("reconexion", "07 · Mensualidad y reconexión", "Cobranza", "Muestra operativa disponible",
         (("Mensualidad sin descuento", "S/89,00"), ("Reconexión simulada", "S/15,00"),
          ("Total del ejemplo", "S/104,00")),
         ("¿Se muestran ambos conceptos por separado y el motivo de la reconexión?",
          "¿Qué tratamiento y descripción debe tener cada concepto en la emisión fiscal?"),
         "S/89,00 + S/15,00 = S/104,00. La muestra no ejecuta cortes ni reconexiones de red."),
    case("pendiente", "08 · Pago informado y por confirmar", "Cobranza", "Muestra operativa disponible",
         (("Conceptos", "Mensualidad S/89,00 + reconexión S/15,00"),
          ("Importe reportado", "S/104,00 por Yape"), ("Estado", "Por confirmar, dinero ficticio"),
          ("Referencia ilustrativa", "QA-OPERACION-001; no adjuntar un voucher real")),
         ("¿Se necesitan banco, número de operación, fecha, depositante y responsable de validación?",
          "¿Se distingue el reporte del cliente de un pago confirmado y de un rechazo?",
          "¿El comprobante evita mostrar una fecha de cancelación mientras sigue pendiente?"),
         "El estado pendiente debe quedar visible. Revisar la confirmación y su efecto en saldo y caja con una muestra autorizada."),
    case("anulacion", "09 · Pago anulado y trazabilidad", "Cobranza", "Muestra operativa disponible",
         (("Concepto ficticio", "S/25,00"), ("Medio", "Transferencia de muestra"),
          ("Estado", "Pago anulado con motivo, usuario y fecha")),
         ("¿Se conserva el pago original y se explica el efecto sobre deuda y caja?",
          "¿Quién puede anular y qué justificación debe registrar?",
          "¿Se distingue anular un cobro interno de corregir un documento fiscal?"),
         "La anulación interna no emite una nota de crédito ni realiza una devolución bancaria."),
    case("agrupado", "10 · Varios conceptos en una operación", "Facturación", "Caso ilustrativo por validar",
         (("Mensualidad de ejemplo", "S/89,00"), ("Instalación ilustrativa", "S/50,00, valor de prueba"),
          ("Total propuesto", "S/139,00"), ("Agrupación y emisor", "Por confirmar")),
         ("¿Qué conceptos se agrupan y cuáles requieren documentos separados?",
          "¿Pueden pertenecer a distintos periodos o empresas emisoras?",
          "¿Qué descripción, cantidad, precio, descuento e impuesto requiere cada línea?"),
         "S/89,00 + S/50,00 = S/139,00 solo como ejemplo. No fija una tarifa ni autoriza la agrupación fiscal."),
    case("parcial", "11 · Pago parcial, adelanto o saldo a favor", "Facturación", "Caso ilustrativo por definir",
         (("Deuda de referencia", "S/89,00"), ("Entrega hipotética", "S/40,00"),
          ("Diferencia aritmética", "S/49,00 antes de aplicar reglas de descuento")),
         ("¿La empresa admite pagos parciales de mensualidades?",
          "¿Cómo se distinguen adelanto, anticipo, garantía y saldo a favor?",
          "¿Qué autorizaciones, aplicación posterior y comprobantes requiere cada caso?"),
         "Es una pregunta de negocio; no demuestra soporte de pagos parciales ni una liquidación válida."),
    case("caja", "12 · Caja y conciliación de medios de pago", "Caja y migración", "Reporte actual parcial",
         (("Cobro efectivo ilustrativo", "S/79,00"), ("Transferencia confirmada ilustrativa", "S/89,00"),
          ("Yape por confirmar ilustrativo", "S/104,00, separado del confirmado"),
          ("Confirmados del ejemplo", "S/168,00; solo S/79,00 es efectivo"),
          ("Saldo inicial, egresos, arqueo y depósitos", "Por registrar/definir; no asumir cero")),
         ("¿Se concilia por fecha, sede, oficina, cajero y medio de pago?",
          "¿Qué debe incluir el cierre, quién lo aprueba y cómo se trata una diferencia?",
          "¿Qué formatos de depósitos, gastos y arqueo físico faltan?"),
         "No usar esta aritmética como saldo final de caja. El reporte vigente advierte que es un consolidado parcial."),
    case("migracion", "13 · Saldos al migrar del sistema antiguo", "Caja y migración", "Caso ilustrativo por validar",
         (("Código antiguo / nuevo", "LEGADO-DEMO-001 / DEMO-CONT-001"),
          ("Deuda inicial ilustrativa", "S/178,00: dos periodos de S/89,00"),
          ("Pago histórico aplicado", "S/89,00"), ("Saldo ilustrativo al corte", "S/89,00"),
          ("Fecha de corte", "Por acordar antes de importar")),
         ("¿Qué periodos y documentos sustentan el saldo y quién concilia los totales?",
          "¿Cómo se detectan duplicados y se evita volver a generar deuda o comprobantes?",
          "¿Cómo se separan pagos pendientes, anulados y saldos a favor?"),
         "S/178,00 − S/89,00 = S/89,00 en este caso. No se importa ni certifica la cartera real."),
    case("emision", "14 · Borrador y conexión fiscal", "Facturación", "Emisión real pendiente",
         (("Emisor, receptor y tipo de documento", "Por confirmar con Contabilidad"),
          ("Conceptos, descuentos e impuestos", "Reglas por validar; no se calcula un IGV de ejemplo"),
          ("Serie y correlativo oficiales", "Sin asignar"),
          ("Estado fiscal", "Sin envío ni aceptación real de SUNAT")),
         ("¿Cuándo se emite: por periodo, al cobrar u otra regla?",
          "¿Qué proveedor/modalidad corresponde a cada empresa?",
          "¿Qué estados, respuesta, entrega al cliente y consulta necesita el área?",
          "¿Quién administra series durante la coexistencia con el sistema antiguo?"),
         "Los borradores y el simulador no equivalen a emisión real. Revisar campos y decisiones, sin introducir claves o certificados."),
    case("ajustes", "15 · Correcciones y reportes contables", "Facturación", "Alcance pendiente de definir",
         (("Operación hipotética", "Comprobante con receptor o importe incorrecto"),
          ("Corrección y referencia al original", "Procedimiento por acordar"),
          ("Reportes requeridos", "Registro de ventas, conciliación y otros que el área confirme")),
         ("¿Qué notas, bajas, resúmenes o contingencias necesita la operación?",
          "¿Qué columnas, filtros, totales y formatos de exportación usa Contabilidad?",
          "¿Qué alcance de SIRE u otras entregas debe incluirse?"),
         "Registrar las necesidades. Este caso no implementa ni confirma cumplimiento de obligaciones tributarias."),
    case("otros", "16 · Otros datos o procesos faltantes", "Revisión general", "Observaciones abiertas",
         (("Ejemplo de observación", "En pagos por banco falta identificar al depositante para conciliar."),
          ("Cómo describirla", "Pantalla/caso + dato faltante + ejemplo ficticio + resultado esperado")),
         ("¿Hay algún caso cotidiano que no esté representado?",
          "¿Qué debe resolverse antes de migrar y qué puede quedar para una etapa posterior?"),
         "Registrar aquí las necesidades adicionales sin datos personales, claves, firmas ni documentos reales."),
)

CASES_BY_CODE = {item["code"]: item for item in CASES}
