# Generated by Django 5.2.17 on 2026-10-06 15:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0005_dashboard_permissions'),
        ('services', '0019_billingpolicy_reconnection_fee'),
        ('work_orders', '0035_seed_equipment_installation_reasons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ONT', 'ONT / Módem'), ('ROUTER', 'Router'), ('DECODER', 'Decodificador'), ('OTHER', 'Otro equipo')], max_length=20, verbose_name='Tipo')),
                ('brand', models.CharField(max_length=80, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Número de serie')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='Dirección MAC')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible para asignar'), ('ASSIGNED', 'Asignado'), ('REVIEW', 'Retirado / por revisar'), ('DAMAGED', 'Dañado')], default='AVAILABLE', editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='organization.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_equipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo de abonado',
                'verbose_name_plural': 'Equipos de abonados',
                'ordering': ['serial_number', 'mac_address', 'pk'],
                'permissions': [('assign_equipment', 'Puede asignar y retirar equipos de abonados')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code_snapshot', models.CharField(max_length=80)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Observación')),
                ('removed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('removal_reason', models.CharField(blank=True, max_length=500, verbose_name='Motivo del retiro')),
                ('return_status', models.CharField(blank=True, choices=[('AVAILABLE', 'Disponible para asignar'), ('ASSIGNED', 'Asignado'), ('REVIEW', 'Retirado / por revisar'), ('DAMAGED', 'Dañado')], max_length=20)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assignments', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='equipment.equipment')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_returns', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assignments', to='services.subscription')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assignments', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Asignación de equipo',
                'verbose_name_plural': 'Historial de equipos',
                'ordering': ['-assigned_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('AVAILABLE', 'Disponible para asignar'), ('ASSIGNED', 'Asignado'), ('REVIEW', 'Retirado / por revisar'), ('DAMAGED', 'Dañado')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible para asignar'), ('ASSIGNED', 'Asignado'), ('REVIEW', 'Retirado / por revisar'), ('DAMAGED', 'Dañado')], max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='equipment.equipment')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revisión de equipo',
                'verbose_name_plural': 'Revisiones de equipos',
                'ordering': ['-reviewed_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['branch', 'status'], name='equipment_branch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('serial_number', ''), _negated=True), models.Q(('mac_address', ''), _negated=True), _connector='OR'), name='equipment_has_identifier'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('serial_number',), name='equipment_unique_serial', violation_error_message='Ya existe un equipo con ese número de serie.'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(condition=models.Q(('mac_address', ''), _negated=True), fields=('mac_address',), name='equipment_unique_mac', violation_error_message='Ya existe un equipo con esa dirección MAC.'),
        ),
        migrations.AddConstraint(
            model_name='equipmentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('equipment',), name='equipment_one_active_assignment'),
        ),
        migrations.AddConstraint(
            model_name='equipmentassignment',
            constraint=models.CheckConstraint(condition=models.Q(('removed_at__isnull', True), ('removed_at__gte', models.F('assigned_at')), _connector='OR'), name='equipment_return_after_assignment'),
        ),
        migrations.AddConstraint(
            model_name='equipmentassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('removal_reason', ''), ('removed_at__isnull', True), ('removed_by__isnull', True), ('return_status', '')), models.Q(('removed_at__isnull', False), ('removed_by__isnull', False), ('return_status__in', ['AVAILABLE', 'REVIEW', 'DAMAGED']), models.Q(('removal_reason', ''), _negated=True)), _connector='OR'), name='equipment_complete_return'),
        ),
    ]
