# Generated by Django 5.2.17 on 2026-10-09 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0023_charge_period_start_charge_source_cut_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_ruc', models.CharField(max_length=11)),
                ('period', models.DateField(help_text='Primer día del periodo tributario seleccionado')),
                ('source', models.CharField(choices=[('OSIPTEL', 'SICV antiguo · OSIPTEL'), ('RVIE', 'SIRE · archivo de comparación')], max_length=10)),
                ('filename', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_count', models.PositiveIntegerField()),
                ('line_count', models.PositiveIntegerField()),
                ('metadata', models.JSONField(default=dict)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.issuer')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'permissions': [('view_workspace', 'Consultar conciliación contable'), ('import_reports', 'Importar reportes para conciliación'), ('review_documents', 'Anotar y clasificar evidencia contable')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=2)),
                ('series', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('issue_date', models.DateField()),
                ('receiver_document', models.CharField(blank=True, max_length=20)),
                ('receiver_name', models.CharField(blank=True, max_length=250)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('base', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('local_state', models.CharField(blank=True, max_length=60)),
                ('sunat_state', models.CharField(blank=True, max_length=60)),
                ('flags', models.JSONField(default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounting.importbatch')),
            ],
            options={
                'ordering': ['issue_date', 'document_type', 'series', 'number', 'pk'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('concept', models.CharField(blank=True, max_length=160)),
                ('technology', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=18)),
                ('base', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('flags', models.JSONField(default=list)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.document')),
            ],
            options={
                'ordering': ['source_row', 'pk'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=2000)),
                ('concept', models.CharField(blank=True, max_length=160)),
                ('technology', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='accounting.document')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='accounting.line')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CompanyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.issuer')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_access_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_access', 'Administrar acceso contable por empresa')],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('user', 'issuer'), name='accounting_user_issuer_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['issuer', 'period', 'source'], name='accounting_period_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('issuer', 'period', 'source', 'sha256'), name='accounting_import_unique'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('batch', 'document_type', 'series', 'number'), name='accounting_document_unique'),
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.UniqueConstraint(fields=('document', 'source_row'), name='accounting_line_row_unique'),
        ),
    ]
