# Generated by Django 5.2.17 on 2026-10-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sire_state',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='document',
            name='source_details',
            field=models.JSONField(default=dict),
        ),
    ]
