# Generated by Django 5.2.17 on 2026-10-10 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_native_rvie_evidence'),
        ('payments', '0026_alter_charge_status_debtadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=80)),
                ('number', models.CharField(max_length=40)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('label', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.issuer')),
            ],
            options={
                'ordering': ['bank', 'number'],
                'permissions': [('view_bank', 'Consultar conciliación bancaria por empresa'), ('manage_bank_accounts', 'Configurar cuentas bancarias'), ('import_bank', 'Importar extractos bancarios'), ('reconcile_bank', 'Confirmar y deshacer conciliaciones bancarias')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BankLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('operation', models.CharField(max_length=120)),
                ('operation_key', models.CharField(db_index=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fingerprint', models.CharField(max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.bankaccount')),
            ],
            options={
                'ordering': ['date', 'pk'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BankEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='accounting.bankaccount')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='accounting.bankline')),
            ],
            options={
                'ordering': ['-pk'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BankMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=500)),
                ('snapshot', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=500)),
                ('cash_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_matches', to='payments.cashentry')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_confirmations', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='accounting.bankline')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_matches', to='payments.payment')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=180)),
                ('sha256', models.CharField(max_length=64)),
                ('original', models.BinaryField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.PositiveIntegerField()),
                ('new_count', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='accounting.bankaccount')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lines', models.ManyToManyField(related_name='statements', to='accounting.bankline')),
            ],
            options={
                'ordering': ['-pk'],
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('bank', 'number', 'currency'), name='bank_account_identity_unique'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'PEN')), name='bank_account_pen_only'),
        ),
        migrations.AddConstraint(
            model_name='bankline',
            constraint=models.UniqueConstraint(fields=('account', 'external_id'), name='bank_external_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='bankline',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='bank_line_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='bankmatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cash_entry__isnull', True), ('payment__isnull', False)), models.Q(('cash_entry__isnull', False), ('payment__isnull', True)), _connector='OR'), name='bank_match_one_target'),
        ),
        migrations.AddConstraint(
            model_name='bankmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('line',), name='bank_line_one_active_match'),
        ),
        migrations.AddConstraint(
            model_name='bankmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('payment__isnull', False)), fields=('payment',), name='bank_payment_one_active_match'),
        ),
        migrations.AddConstraint(
            model_name='bankmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('cash_entry__isnull', False)), fields=('cash_entry',), name='bank_deposit_one_active_match'),
        ),
        migrations.AddConstraint(
            model_name='bankmatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('released_at__isnull', True), ('released_by__isnull', True)), models.Q(('active', False), ('released_at__isnull', False), ('released_by__isnull', False)), _connector='OR'), name='bank_release_complete'),
        ),
        migrations.AddConstraint(
            model_name='bankstatement',
            constraint=models.UniqueConstraint(fields=('account', 'sha256'), name='bank_statement_hash_unique'),
        ),
    ]
