# Generated by Django 5.2.17 on 2026-10-10 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_bankaccount_bankline_bankevent_bankmatch_and_more'),
        ('payments', '0026_alter_charge_status_debtadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_ruc', models.CharField(max_length=11)),
                ('period', models.CharField(choices=[('DAY', 'Diario'), ('FORTNIGHT', 'Quincenal'), ('MONTH', 'Mensual'), ('YEAR', 'Anual')], max_length=10)),
                ('revision', models.PositiveIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=16)),
                ('warning_percent', models.PositiveSmallIntegerField(default=80)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_key', models.UUIDField(unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.issuer')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': [('view_revenue', 'Consultar recaudación por empresa'), ('manage_revenue_rules', 'Configurar alertas administrativas de recaudación')],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('issuer', 'period', 'revision'), name='revenue_rule_revision_unique'), models.CheckConstraint(condition=models.Q(('limit__gt', 0)), name='revenue_rule_positive_limit'), models.CheckConstraint(condition=models.Q(('warning_percent__gte', 1), ('warning_percent__lte', 100)), name='revenue_rule_warning_range'), models.CheckConstraint(condition=models.Q(('period__in', ['DAY', 'FORTNIGHT', 'MONTH', 'YEAR'])), name='revenue_rule_valid_period')],
            },
        ),
    ]
