# Generated by Django 5.2.17 on 2026-09-07 22:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customeraddress_electrical_supply_code'),
        ('organization', '0002_seed_sedes_reales'),
        ('services', '0007_alter_plan_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=8, unique=True, verbose_name='Serie')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Último correlativo emitido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Correlativo de recibos',
                'verbose_name_plural': 'Correlativos de recibos',
                'ordering': ['series'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(choices=[('MONTHLY', 'Mensualidad'), ('INSTALLATION', 'Instalación'), ('ANNEX', 'Anexo'), ('REACTIVATION', 'Reconexión'), ('OTHER', 'Otro concepto')], max_length=20, verbose_name='Concepto')),
                ('description', models.CharField(max_length=160, verbose_name='Detalle')),
                ('period', models.DateField(blank=True, help_text='Primer día del mes que cubre el cargo. Solo para mensualidades.', null=True, verbose_name='Periodo facturado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto emitido')),
                ('due_date', models.DateField(verbose_name='Vence el')),
                ('early_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento por pronto pago')),
                ('discount_deadline', models.DateField(blank=True, null=True, verbose_name='Pronto pago hasta')),
                ('cut_date', models.DateField(blank=True, null=True, verbose_name='Fecha de corte prevista')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIALLY_PAID', 'Pago parcial'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='customers.customer', verbose_name='Abonado')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='services.subscription', verbose_name='Suscripción')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['due_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto recibido')),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TRANSFER', 'Transferencia'), ('DEPOSIT', 'Depósito en cuenta'), ('CARD', 'Tarjeta')], max_length=20, verbose_name='Método de pago')),
                ('reference', models.CharField(blank=True, help_text='Obligatorio para todo método que no sea efectivo.', max_length=60, verbose_name='Número de operación')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Recibido el')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Observación')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registrado'), ('VOIDED', 'Anulado')], default='REGISTERED', max_length=20, verbose_name='Estado')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='Anulado el')),
                ('void_reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo de la anulación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='organization.branch', verbose_name='Sede que cobró')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer', verbose_name='Abonado')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_voided', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-received_at', '-pk'],
                'permissions': [('void_payment', 'Puede anular pagos registrados')],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto aplicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.charge', verbose_name='Cargo')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Aplicación de pago',
                'verbose_name_plural': 'Aplicaciones de pago',
                'ordering': ['charge__due_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=8, verbose_name='Serie')),
                ('number', models.PositiveIntegerField(verbose_name='Correlativo')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Emitido el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Comprobante de pago',
                'verbose_name_plural': 'Comprobantes de pago',
                'ordering': ['-issued_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_charge_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(condition=models.Q(('concept', 'MONTHLY')), fields=('subscription', 'period'), name='payments_charge_unique_monthly_period'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'charge'), name='payments_allocation_unique_payment_charge'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('series', 'number'), name='payments_receipt_unique_series_number'),
        ),
    ]
