# Generated by Django 5.2.17 on 2026-09-08 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customeraddress_electrical_supply_code'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto comprometido')),
                ('committed_date', models.DateField(verbose_name='Se compromete a pagar el')),
                ('reason', models.CharField(max_length=200, verbose_name='Motivo del compromiso')),
                ('status', models.CharField(choices=[('ACTIVE', 'Vigente'), ('FULFILLED', 'Cumplido'), ('BROKEN', 'Incumplido'), ('CANCELLED', 'Anulado')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charges', models.ManyToManyField(related_name='commitments', to='payments.charge', verbose_name='Cargos comprometidos')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_commitments', to='customers.customer', verbose_name='Abonado')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_commitments_granted', to=settings.AUTH_USER_MODEL, verbose_name='Concedido por')),
            ],
            options={
                'verbose_name': 'Compromiso de pago',
                'verbose_name_plural': 'Compromisos de pago',
                'ordering': ['-committed_date', '-pk'],
                'permissions': [('grant_paymentcommitment', 'Puede conceder compromisos de pago')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_commitment_amount_positive')],
            },
        ),
    ]
