# Generated by Django 5.2.17 on 2026-09-08 02:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_commitment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='auto_update',
            field=models.BooleanField(default=True, verbose_name='Actualizar automáticamente'),
        ),
        migrations.AddField(
            model_name='charge',
            name='currency',
            field=models.CharField(default='PEN', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='charge',
            name='issued_on',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='charge',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Cubre hasta'),
        ),
        migrations.AddField(
            model_name='charge',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=Decimal('1.00000'), max_digits=12, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='payment',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_collected', to=settings.AUTH_USER_MODEL, verbose_name='Cobrador'),
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de pago'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='paymentcommitment',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_commitments_authorized', to=settings.AUTH_USER_MODEL, verbose_name='Autoriza'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('DEPOSIT', 'Depósito'), ('TRANSFER', 'Transferencia'), ('CARD', 'Tarjeta de crédito'), ('CHEQUE', 'Cheque'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(help_text='Quien registro el cobro en el sistema.', on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('REGISTERED', 'Cancelado'), ('VOIDED', 'Anulado')], default='REGISTERED', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='paymentcommitment',
            name='granted_by',
            field=models.ForeignKey(help_text='Quien registro el compromiso en el sistema.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_commitments_granted', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
