# Generated by Django 5.2.17 on 2026-09-08 23:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_comprobante_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto emitido'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='early_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento por pronto pago'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=Decimal('1.00000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))], verbose_name='Cantidad'),
        ),
    ]
