# Generated by Django 5.2.17 on 2026-09-10 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_charge_amount_alter_charge_early_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identificador estable. No cambia aunque se corrija el nombre.', max_length=80, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Concepto')),
                ('family', models.CharField(choices=[('MONTHLY', 'Mensualidad'), ('INSTALLATION', 'Instalación'), ('ANNEX', 'Anexo'), ('REACTIVATION', 'Reconexión'), ('OTHER', 'Otro concepto')], default='OTHER', help_text='El comportamiento del sistema al que responde el concepto.', max_length=20, verbose_name='Familia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Concepto cobrable',
                'verbose_name_plural': 'Conceptos cobrables',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='charge',
            name='concept_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='payments.chargeconcept', verbose_name='Concepto del catálogo'),
        ),
    ]
