# Generated by Django 5.2.17 on 2026-09-12 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_retirar_talonario_r001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('business_name', models.CharField(max_length=120, verbose_name='Razón social')),
                ('ruc', models.CharField(max_length=11, verbose_name='RUC')),
                ('address', models.CharField(blank=True, max_length=160, verbose_name='Dirección fiscal')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa emisora',
                'verbose_name_plural': 'Empresas emisoras',
                'ordering': ['business_name'],
            },
        ),
        migrations.AddField(
            model_name='receiptsequence',
            name='document_title',
            field=models.CharField(default='RECIBO DE SERVICIO PÚBLICO ELECTRÓNICO', max_length=60, verbose_name='Título del documento'),
        ),
        migrations.AddField(
            model_name='receiptsequence',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequences', to='payments.issuer', verbose_name='Empresa emisora'),
        ),
    ]
