# Generated by Django 5.2.17 on 2026-09-13 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_office_is_deposit'),
        ('payments', '0010_sembrar_empresas_emisoras'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Orden en la lista de la oficina')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_links', to='organization.office', verbose_name='Oficina')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_links', to='payments.receiptsequence', verbose_name='Talonario')),
            ],
            options={
                'verbose_name': 'Talonario de una oficina',
                'verbose_name_plural': 'Talonarios por oficina',
                'ordering': ['office', 'position', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='receiptsequence',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='receipt_sequences', through='payments.OfficeSequence', to='organization.office', verbose_name='Oficinas que lo ofrecen'),
        ),
        migrations.AddConstraint(
            model_name='officesequence',
            constraint=models.UniqueConstraint(fields=('office', 'sequence'), name='unique_sequence_per_office'),
        ),
    ]
