# Generated by Django 5.2.17 on 2026-09-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_padron_de_talonarios_por_oficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptsequence',
            name='print_format',
            field=models.CharField(choices=[('SHEET', 'Media hoja apaisada'), ('TICKET', 'Tique en vertical')], default='SHEET', max_length=10, verbose_name='Formato impreso'),
        ),
    ]
