# Generated by Django 5.2.17 on 2026-09-13 02:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_boletas_en_tique'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcommitment',
            name='representative',
            field=models.CharField(blank=True, max_length=120, verbose_name='Representante'),
        ),
        migrations.AddField(
            model_name='paymentcommitment',
            name='representative_document',
            field=models.CharField(blank=True, max_length=20, verbose_name='DNI del representante'),
        ),
        migrations.AlterField(
            model_name='paymentcommitment',
            name='reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observaciones'),
        ),
        migrations.CreateModel(
            name='PaymentCommitmentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Cuota')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('due_date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.paymentcommitment', verbose_name='Compromiso')),
            ],
            options={
                'verbose_name': 'Cuota del compromiso',
                'verbose_name_plural': 'Cuotas del compromiso',
                'ordering': ['commitment', 'number'],
                'constraints': [models.UniqueConstraint(fields=('commitment', 'number'), name='unique_installment_number_per_commitment')],
            },
        ),
    ]
