# Generated by Django 5.2.17 on 2026-09-30 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_equipment_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-issued_at', '-pk'], 'permissions': [('view_cash_closing', 'Puede ver el cierre de caja')], 'verbose_name': 'Comprobante de pago', 'verbose_name_plural': 'Comprobantes de pago'},
        ),
    ]
