# Generated by Django 5.2.17 on 2026-10-01 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_permiso_cierre_de_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-received_at', '-pk'], 'permissions': [('confirm_payment', 'Puede confirmar cobros pendientes'), ('void_payment', 'Puede anular pagos registrados')], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='payment',
            name='full_monthly_only',
            field=models.BooleanField(default=False, editable=False, help_text='Regla aplicada al preparar el cobro. Los registros anteriores conservan su política.'),
        ),
        migrations.CreateModel(
            name='PaymentOperationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REGISTERED', 'Cobro registrado'), ('PENDING', 'Pendiente registrado'), ('CONFIRMED', 'Pendiente confirmado'), ('VOIDED', 'Pago anulado')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_events', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Evento de cobranza',
                'verbose_name_plural': 'Eventos de cobranza',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(editable=False, unique=True)),
                ('fingerprint', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='payments.payment')),
            ],
        ),
    ]
