# Generated by Django 5.2.17 on 2026-10-02 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_alter_payment_options_payment_full_monthly_only_and_more'),
        ('work_orders', '0035_seed_equipment_installation_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Cubre desde'),
        ),
        migrations.AddField(
            model_name='charge',
            name='source_cut_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconnection_charge', to='work_orders.workorder', verbose_name='Corte que origina la reconexión'),
        ),
    ]
