# Generated by Django 5.2.17 on 2026-10-09 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_dashboard_permissions'),
        ('payments', '0024_seed_econet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('declared_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=14)),
                ('explanation', models.CharField(blank=True, max_length=500)),
                ('snapshot', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('SUBMITTED', 'En revisión'), ('APPROVED', 'Aprobada')], default='OPEN', max_length=12)),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('opening_reason', models.CharField(max_length=300)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.office')),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='following', to='payments.cashsession')),
            ],
            options={
                'ordering': ['-business_date', '-pk'],
                'permissions': [('operate_cash', 'Puede operar su caja en oficinas autorizadas'), ('review_cash', 'Puede revisar y aprobar cajas de sus oficinas')],
            },
        ),
        migrations.CreateModel(
            name='CashEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('close', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payments.cashclose')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payments.cashsession')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PAYMENT', 'Cobro'), ('VOID', 'Anulación de cobro'), ('EXPENSE', 'Gasto en efectivo'), ('DEPOSIT', 'Depósito de caja al banco'), ('INCOME', 'Otro ingreso en efectivo'), ('GUARANTEE', 'Garantía recibida en efectivo'), ('REVERSAL', 'Reversión de movimiento')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(max_length=20)),
                ('issuer_label', models.CharField(blank=True, max_length=150)),
                ('issuer_ruc', models.CharField(blank=True, max_length=11)),
                ('description', models.CharField(max_length=300)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('account', models.CharField(blank=True, max_length=100)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_key', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('fingerprint', models.CharField(blank=True, editable=False, max_length=64)),
                ('deposit_key', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.issuer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.payment')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='payments.cashentry')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='payments.cashsession')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='cashclose',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closes', to='payments.cashsession'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(fields=('office', 'cashier', 'business_date'), name='cash_session_day_unique'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APPROVED'), _negated=True), fields=('office', 'cashier'), name='cash_session_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(condition=models.Q(('opening_amount__gte', 0)), name='cash_opening_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'SUBMITTED', 'APPROVED'])), name='cash_session_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='cashentry',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False)), fields=('payment', 'kind'), name='cash_payment_kind_unique'),
        ),
        migrations.AddConstraint(
            model_name='cashentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='cash_entry_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='cashclose',
            constraint=models.UniqueConstraint(fields=('session', 'revision'), name='cash_close_revision_unique'),
        ),
    ]
