# Generated by Django 5.2.17 on 2026-10-10 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_cashclose_cashsession_cashevent_cashentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIALLY_PAID', 'Pago parcial'), ('PAID', 'Pagado'), ('ADJUSTED', 'Regularizado por ajuste'), ('CANCELLED', 'Anulado')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='DebtAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=500)),
                ('reference', models.CharField(max_length=120)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('request_key', models.UUIDField(unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('expected_state', models.CharField(max_length=64)),
                ('request_snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de aprobación'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('result_snapshot', models.JSONField(default=dict)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='payments.charge')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_requests', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='payments.debtadjustment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': [('request_debt_adjustment', 'Solicitar ajustes comerciales de deuda'), ('review_debt_adjustment', 'Revisar ajustes de deuda en sus sedes')],
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('charge',), name='debt_one_pending_per_charge'), models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED'])), fields=('reversal_of',), name='debt_reversal_once'), models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('reversal_of__isnull', True)), models.Q(('amount__lt', 0), ('reversal_of__isnull', False)), _connector='OR'), name='debt_adjustment_sign'), models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('status', 'PENDING')), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('status__in', ['APPROVED', 'REJECTED'])), _connector='OR'), name='debt_review_complete'), models.CheckConstraint(condition=models.Q(('reviewed_by__isnull', True), models.Q(('reviewed_by', models.F('requested_by')), _negated=True), _connector='OR'), name='debt_no_self_review')],
            },
        ),
    ]
