# Generated by Django 5.2.17 on 2026-10-10 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_incomplete_registration_discard'),
        ('organization', '0005_dashboard_permissions'),
        ('payments', '0026_alter_charge_status_debtadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'paid_at'], name='payment_status_paid_idx'),
        ),
    ]
