# Generated by Django 5.2.17 on 2026-10-01 21:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_incomplete_registration_discard'),
        ('organization', '0004_office_is_deposit'),
        ('payments', '0021_permiso_cierre_de_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_key', models.UUIDField(editable=False, unique=True)),
                ('request_fingerprint', models.CharField(editable=False, max_length=64)),
                ('document_type', models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta de venta'), ('14', 'Recibo de servicios públicos')], max_length=2)),
                ('proposed_issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('currency', models.CharField(max_length=3)),
                ('source_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('snapshot', models.JSONField(editable=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador para revisión'), ('CANCELLED', 'Borrador descartado')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_fiscal_drafts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_drafts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_drafts', to='customers.customer')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_drafts', to='payments.issuer')),
            ],
            options={
                'verbose_name': 'Borrador de facturación',
                'verbose_name_plural': 'Borradores de facturación',
                'ordering': ['-created_at', '-pk'],
                'permissions': [('cancel_fiscaldocument', 'Puede descartar borradores de facturación')],
            },
        ),
        migrations.CreateModel(
            name='FiscalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Preparado'), ('CANCELLED', 'Descartado')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='fiscal.fiscaldocument')),
            ],
            options={
                'verbose_name': 'Evento de preparación fiscal',
                'verbose_name_plural': 'Eventos de preparación fiscal',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FiscalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('PENDING', 'Por confirmar'), ('CONTRIBUTOR', 'SEE del contribuyente'), ('SFS', 'Facturador SUNAT'), ('OSE', 'SEE OSE')], default='PENDING', max_length=20, verbose_name='Modalidad de emisión')),
                ('provider_name', models.CharField(blank=True, help_text='Nombre solamente. No guardar claves ni certificados aquí.', max_length=120, verbose_name='Proveedor o herramienta')),
                ('document_types', models.JSONField(blank=True, default=list, verbose_name='Documentos previstos')),
                ('billing_trigger', models.CharField(choices=[('PENDING', 'Por confirmar'), ('MONTHLY', 'Al generar la mensualidad'), ('PAYMENT', 'Al registrar el cobro'), ('OTHER', 'Otra regla documentada')], default='PENDING', max_length=20, verbose_name='Momento de emisión')),
                ('tax_rules_confirmed', models.BooleanField(default=False, verbose_name='Tratamiento tributario confirmado')),
                ('receiver_rules_confirmed', models.BooleanField(default=False, verbose_name='Reglas del receptor confirmadas')),
                ('confirmation_reference', models.TextField(blank=True, help_text='Decisiones y fecha de confirmación. Esta referencia no habilita la emisión.', verbose_name='Referencia de la validación contable')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_profile', to='payments.issuer', verbose_name='Empresa emisora')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración fiscal',
                'verbose_name_plural': 'Configuraciones fiscales',
            },
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.CheckConstraint(condition=models.Q(('source_total__gt', 0)), name='fiscal_positive_source_total'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancel_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('status', 'DRAFT')), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'CANCELLED'), models.Q(('cancel_reason', ''), _negated=True)), _connector='OR'), name='fiscal_draft_state_consistent'),
        ),
    ]
