# Generated by Django 5.2.17 on 2026-10-02 13:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_fiscalprofilerevision'),
        ('payments', '0022_alter_payment_options_payment_full_monthly_only_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OseSimulatorReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('result', models.CharField(max_length=20)),
                ('ticket', models.CharField(max_length=100)),
                ('pending_queries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('DISABLED', 'Deshabilitado'), ('SIMULATOR', 'Simulador local de pruebas'), ('PENDING', 'Proveedor pendiente de integrar')], default='DISABLED', max_length=20)),
                ('provider_name', models.CharField(blank=True, max_length=120, verbose_name='Proveedor previsto')),
                ('test_endpoint', models.URLField(blank=True, verbose_name='URL del servicio de pruebas')),
                ('production_endpoint', models.URLField(blank=True, verbose_name='URL del servicio de producción')),
                ('username_setting', models.CharField(blank=True, max_length=100, verbose_name='Variable para el usuario')),
                ('password_setting', models.CharField(blank=True, max_length=100, verbose_name='Variable para la clave')),
                ('certificate_setting', models.CharField(blank=True, max_length=100, verbose_name='Variable para el certificado')),
                ('certificate_password_setting', models.CharField(blank=True, max_length=100, verbose_name='Variable para la clave del certificado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ose_connection', to='payments.issuer')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexión OSE prevista',
                'verbose_name_plural': 'Conexiones OSE previstas',
                'permissions': [('configure_ose', 'Puede configurar la conexión OSE prevista'), ('simulate_ose', 'Puede ejecutar pruebas simuladas de OSE')],
            },
        ),
        migrations.CreateModel(
            name='OseConnectionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='fiscal.oseconnection')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OseSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_key', models.UUIDField(editable=False, unique=True)),
                ('request_fingerprint', models.CharField(editable=False, max_length=64)),
                ('scenario', models.CharField(choices=[('ACCEPTED', 'Aceptación simulada'), ('OBSERVED', 'Aceptación con observación simulada'), ('REJECTED', 'Rechazo simulado'), ('DELAYED', 'Respuesta pendiente y consulta posterior'), ('LOST_REPLY', 'Recepción simulada con respuesta perdida'), ('NOT_SENT', 'Falla temporal antes de recibir el envío')], max_length=20)),
                ('connection_snapshot', models.JSONField(editable=False)),
                ('payload', models.JSONField(editable=False)),
                ('payload_hash', models.CharField(editable=False, max_length=64)),
                ('state', models.CharField(choices=[('READY', 'Prueba preparada'), ('WORKING', 'Prueba en ejecución'), ('PROCESSING', 'Prueba pendiente de consulta'), ('UNCERTAIN', 'Prueba con resultado desconocido: consultar'), ('RETRYABLE', 'Prueba sin envío recibido: reintentar'), ('ACCEPTED', 'Aceptación simulada · sin validez tributaria'), ('OBSERVED', 'Observación simulada · sin validez tributaria'), ('REJECTED', 'Rechazo simulado · sin efecto fiscal')], default='READY', max_length=20)),
                ('ticket', models.CharField(blank=True, max_length=100)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_until', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ose_simulations', to='fiscal.fiscaldocument')),
            ],
            options={
                'verbose_name': 'Prueba simulada OSE',
                'verbose_name_plural': 'Pruebas simuladas OSE',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OseSimulationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('token', models.UUIDField(editable=False, unique=True)),
                ('operation', models.CharField(choices=[('SUBMIT', 'Envío simulado'), ('QUERY', 'Consulta simulada')], max_length=10)),
                ('outcome', models.CharField(choices=[('RUNNING', 'En ejecución'), ('DONE', 'Finalizado'), ('FAILED', 'Sin respuesta concluyente'), ('ABANDONED', 'Ejecución interrumpida')], default='RUNNING', max_length=20)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='fiscal.osesimulation')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='OseSimulationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Prueba preparada'), ('STARTED', 'Intento iniciado'), ('FINISHED', 'Intento finalizado'), ('RECOVERED', 'Ejecución interrumpida recuperada')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='fiscal.osesimulation')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='oseconnection',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['DISABLED', 'SIMULATOR', 'PENDING'])), name='ose_connection_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='osesimulation',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['READY', 'WORKING', 'PROCESSING', 'UNCERTAIN', 'RETRYABLE', 'ACCEPTED', 'OBSERVED', 'REJECTED'])), name='ose_simulation_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='osesimulation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lease_token__isnull', False), ('lease_until__isnull', False), ('state', 'WORKING')), models.Q(models.Q(('state', 'WORKING'), _negated=True), ('lease_token__isnull', True), ('lease_until__isnull', True)), _connector='OR'), name='ose_simulation_lease_consistent'),
        ),
        migrations.AddConstraint(
            model_name='osesimulationattempt',
            constraint=models.UniqueConstraint(fields=('simulation', 'number'), name='ose_simulation_attempt_unique'),
        ),
    ]
