# Generated by Django 5.2.17 on 2026-10-02 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_osesimulatorreceipt_oseconnection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='osesimulation',
            constraint=models.CheckConstraint(condition=models.Q(('scenario__in', ['ACCEPTED', 'OBSERVED', 'REJECTED', 'DELAYED', 'LOST_REPLY', 'NOT_SENT'])), name='ose_simulation_scenario_valid'),
        ),
    ]
