# Generated by Django 5.2.17 on 2026-08-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('DECODER', 'Decodificador'), ('ROUTER', 'Router'), ('ONT', 'ONT/Módem'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serial_or_mac', models.CharField(max_length=100, unique=True, verbose_name='Número de serie o MAC')),
                ('status', models.CharField(choices=[('IN_STOCK', 'En stock'), ('ASSIGNED', 'Asignado'), ('RETIRED', 'Retirado'), ('DAMAGED', 'Dañado/Baja')], default='IN_STOCK', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['equipment_type', 'brand', 'model'],
            },
        ),
    ]
