"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Configuracion por variables de entorno
# Se usa unicamente la libreria estandar (os.environ) para no agregar dependencias.
# Si existe un archivo .env en la raiz del proyecto se carga como conveniencia
# para el entorno local. Las variables ya presentes en el entorno tienen prioridad.

def load_dotenv(path):
    """Carga pares CLAVE=VALOR desde un archivo .env sin sobreescribir el entorno."""
    if not path.exists():
        return
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    """Convierte una variable de entorno a booleano de forma explicita."""
    value = os.environ.get(name)
    if value is None or value.strip() == '':
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on', 'si')


def env_list(name, default=()):
    """Convierte una variable separada por comas en una lista limpia."""
    value = os.environ.get(name)
    if value is None or value.strip() == '':
        return list(default)
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# La clave nunca se escribe en el repositorio. Cada entorno (local, pruebas, QA,
# produccion) define su propia DJANGO_SECRET_KEY.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Valor solo para desarrollo local con DEBUG=True. No usar fuera de local.
        SECRET_KEY = 'dev-only-insecure-key-not-for-production'
    else:
        raise ImproperlyConfigured(
            'Falta la variable de entorno DJANGO_SECRET_KEY. '
            'Definela en el entorno o en el archivo .env (ver .env.example).'
        )

# Lista separada por comas. Sin valor por defecto permisivo: nunca ['*'].
ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    default=('localhost', '127.0.0.1') if DEBUG else (),
)


# ---------------------------------------------------------------------
# Integracion RENIEC / SUNAT (consulta de DNI y RUC)
#
# Se usa para autocompletar nombres/apellidos (DNI) o razon social
# (RUC) en el registro de clientes (Pantalla 3). El proveedor por
# defecto es Peru API (https://peruapi.com), elegido porque su plan
# gratuito incluye tanto RUC como DNI (a diferencia de otras opciones
# evaluadas). La autenticacion va como parametro de consulta
# "api_token", no como header Authorization.
#
# Ver docs/consulta_documento_externa.md para el detalle de limites
# del plan gratuito, formato de respuesta y consideraciones sobre
# proteccion de datos personales.
#
# SUNAT_API_TOKEN: token gratuito obtenido en https://peruapi.com
# (panel tras registrarse). Si no se configura, el boton "Obtener
# datos" mostrara un aviso indicando que el servicio no esta
# disponible, sin afectar el resto del registro manual del cliente
# (la consulta automatica es siempre opcional).
# ---------------------------------------------------------------------

SUNAT_API_TOKEN = os.environ.get('SUNAT_API_TOKEN', '')

SUNAT_API_BASE_URL = os.environ.get(
    'SUNAT_API_BASE_URL',
    'https://peruapi.com/api',
).rstrip('/')

SUNAT_API_TIMEOUT = float(os.environ.get('SUNAT_API_TIMEOUT', '8'))


# Application definition

INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # SICV
    'apps.accounts',
    'apps.organization',
    'apps.customers',
    'apps.services',
    'apps.contracts',
    'apps.work_orders',
    'apps.technicians',
    'apps.inventory',
    'apps.audit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Desarrollo y CI usan SQLite. PostgreSQL se configurara en una actividad
# posterior mediante variables de entorno (ver docs/configuration.md).

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Destino de collectstatic para un futuro despliegue. No se usa en desarrollo.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Archivos subidos por los usuarios (evidencias de atención).
# En desarrollo se sirven desde el disco local. En producción solo debe
# cambiar el backend de storage: ningún modelo depende de esta ruta.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

# Redirecciones de autenticación
LOGIN_REDIRECT_URL = '/customers/search/'
LOGOUT_REDIRECT_URL = '/accounts/login/'