"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Configuracion por variables de entorno
# Se usa unicamente la libreria estandar (os.environ) para no agregar dependencias.
# Si existe un archivo .env en la raiz del proyecto se carga como conveniencia
# para el entorno local. Las variables ya presentes en el entorno tienen prioridad.

def load_dotenv(path):
    """Carga pares CLAVE=VALOR desde un archivo .env sin sobreescribir el entorno."""
    if not path.exists():
        return
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    """Convierte una variable de entorno a booleano de forma explicita."""
    value = os.environ.get(name)
    if value is None or value.strip() == '':
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on', 'si')


def env_list(name, default=()):
    """Convierte una variable separada por comas en una lista limpia."""
    value = os.environ.get(name)
    if value is None or value.strip() == '':
        return list(default)
    return [item.strip() for item in value.split(',') if item.strip()]


def env_int(name, default=0):
    """Convierte una variable de entorno a entero con un error explicito."""
    value = os.environ.get(name)
    if value is None or value.strip() == '':
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(
            f'La variable {name} debe ser un entero.'
        ) from exc


# Marca explicita del entorno cloud/productivo. CI no la activa: de ese modo
# sigue probando por HTTP/SQLite sin relajar las reglas que usara Azure.
PRODUCTION = env_bool('DJANGO_PRODUCTION', default=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# La clave nunca se escribe en el repositorio. Cada entorno (local, pruebas, QA,
# produccion) define su propia DJANGO_SECRET_KEY.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Valor solo para desarrollo local con DEBUG=True. No usar fuera de local.
        SECRET_KEY = 'dev-only-insecure-key-not-for-production'
    else:
        raise ImproperlyConfigured(
            'Falta la variable de entorno DJANGO_SECRET_KEY. '
            'Definela en el entorno o en el archivo .env (ver .env.example).'
        )

# Lista separada por comas. Sin valor por defecto permisivo: nunca ['*'].
ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    default=('localhost', '127.0.0.1') if DEBUG else (),
)

CSRF_TRUSTED_ORIGINS = env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    default=(),
)

# Azure App Service termina TLS delante de Gunicorn y reenvia el protocolo
# original mediante X-Forwarded-Proto. Django debe confiar solo en ese header
# concreto para reconocer peticiones HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# El hardening se activa al marcar explicitamente el entorno como productivo.
# Los overrides individuales permiten reducir HSTS durante el primer piloto
# sin deshabilitar cookies seguras o la redireccion HTTPS.
SECURE_SSL_REDIRECT = env_bool(
    'DJANGO_SECURE_SSL_REDIRECT',
    default=PRODUCTION,
)
SESSION_COOKIE_SECURE = env_bool(
    'DJANGO_SESSION_COOKIE_SECURE',
    default=PRODUCTION,
)
CSRF_COOKIE_SECURE = env_bool(
    'DJANGO_CSRF_COOKIE_SECURE',
    default=PRODUCTION,
)
SECURE_HSTS_SECONDS = env_int(
    'DJANGO_SECURE_HSTS_SECONDS',
    default=3600 if PRODUCTION else 0,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
    default=False,
)
SECURE_HSTS_PRELOAD = env_bool(
    'DJANGO_SECURE_HSTS_PRELOAD',
    default=False,
)


# ---------------------------------------------------------------------
# Consulta automatica de DNI / RUC
#
# Se usa para autocompletar nombres y apellidos (DNI) o razon social
# (RUC) durante el registro de clientes.
#
# Proveedor activo: JSON.pe.
# La autenticacion se realiza mediante Bearer Token.
#
# Peru API se conserva temporalmente como integracion legada hasta
# completar su retiro definitivo.
#
# La consulta automatica es opcional: si el proveedor no esta
# disponible, el operador puede continuar con el registro manual.
# ---------------------------------------------------------------------

SUNAT_API_TOKEN = os.environ.get('SUNAT_API_TOKEN', '')

SUNAT_API_BASE_URL = os.environ.get(
    'SUNAT_API_BASE_URL',
    'https://peruapi.com/api',
).rstrip('/')

SUNAT_API_TIMEOUT = float(os.environ.get('SUNAT_API_TIMEOUT', '8'))

JSONPE_API_TOKEN = os.environ.get("JSONPE_API_TOKEN", "")

JSONPE_API_BASE_URL = os.environ.get(
    "JSONPE_API_BASE_URL",
    "https://api.json.pe/api",
).rstrip("/")

JSONPE_API_TIMEOUT = float(
    os.environ.get("JSONPE_API_TIMEOUT", "8")
)
# Application definition

INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceros
    # En produccion App Service no debe depender de DEBUG para servir static.
    'whitenoise.runserver_nostatic',
    'rest_framework',
    'rest_framework.authtoken',

    # SICV
    'apps.accounts',
    'apps.organization',
    'apps.customers',
    'apps.services',
    'apps.contracts',
    'apps.work_orders',
    'apps.payments',
    'apps.technicians',
    'apps.inventory',
    'apps.audit',
    'apps.legacy',
    'apps.reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.audit.middleware.ActivityAuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.organization.context_processors.organization',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Local/CI conservan SQLite. Azure usa PostgreSQL Flexible Server sin cambiar
# codigo: basta definir DJANGO_DB_ENGINE=postgresql y las credenciales en los
# App Settings. En modo productivo se rechaza SQLite para evitar desplegar
# accidentalmente una base efimera dentro de App Service.

DB_ENGINE = os.environ.get('DJANGO_DB_ENGINE', 'sqlite').strip().lower()

if DB_ENGINE in ('postgres', 'postgresql', 'django.db.backends.postgresql'):
    required_db_vars = {
        'DJANGO_DB_NAME': os.environ.get('DJANGO_DB_NAME', '').strip(),
        'DJANGO_DB_USER': os.environ.get('DJANGO_DB_USER', '').strip(),
        'DJANGO_DB_PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', '').strip(),
        'DJANGO_DB_HOST': os.environ.get('DJANGO_DB_HOST', '').strip(),
    }
    missing_db_vars = [
        name for name, value in required_db_vars.items() if not value
    ]
    if missing_db_vars:
        raise ImproperlyConfigured(
            'Faltan variables de PostgreSQL: '
            + ', '.join(missing_db_vars)
        )

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': required_db_vars['DJANGO_DB_NAME'],
            'USER': required_db_vars['DJANGO_DB_USER'],
            'PASSWORD': required_db_vars['DJANGO_DB_PASSWORD'],
            'HOST': required_db_vars['DJANGO_DB_HOST'],
            'PORT': os.environ.get('DJANGO_DB_PORT', '5432'),
            'CONN_MAX_AGE': env_int('DJANGO_DB_CONN_MAX_AGE', default=60),
            'OPTIONS': {
                'sslmode': os.environ.get(
                    'DJANGO_DB_SSLMODE',
                    'require',
                ),
            },
        }
    }
elif DB_ENGINE in ('sqlite', 'sqlite3', 'django.db.backends.sqlite3'):
    if PRODUCTION:
        raise ImproperlyConfigured(
            'DJANGO_PRODUCTION=True requiere PostgreSQL; '
            'SQLite no se admite en Azure.'
        )
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise ImproperlyConfigured(
        'DJANGO_DB_ENGINE debe ser sqlite o postgresql.'
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Hasher rapido EXCLUSIVAMENTE durante la ejecucion de la suite.
#
# El costo de la suite no esta en la logica sino en el setUp: los escenarios de
# prueba crean varios usuarios por cada prueba y cada create_user() ejecuta
# PBKDF2 con cientos de miles de iteraciones. Medido en este proyecto: 536
# pruebas en ~34 minutos, y por ese motivo el timeout de CI se amplio a 30.
# Con MD5 la suite completa baja a minutos, en local y en CI, sin cambiar
# ninguna validacion ni ninguna prueba.
#
# La condicion es deliberadamente estrecha: se exige que el comando de gestion
# invocado sea exactamente "test" (manage.py test), no que la palabra aparezca
# en algun argumento. Cualquier otro arranque -runserver, gunicorn, migrate,
# shell- conserva PBKDF2, de modo que ningun entorno real puede quedar con
# hasheo debil por accidente. Fuera de la suite esta lista NO se declara y
# Django usa su valor por defecto.
#
# MD5 es inseguro para contrasenas reales. Aqui es correcto porque las
# contrasenas de prueba se crean y se destruyen con la base de datos de test.

if sys.argv[1:2] == ['test']:
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.environ.get('DJANGO_STATIC_URL', '/static/')
STATIC_ROOT = Path(
    os.environ.get('DJANGO_STATIC_ROOT', BASE_DIR / 'staticfiles')
)

# En Azure, collectstatic crea el manifiesto y WhiteNoise entrega los assets
# con nombre versionado/compresion. Local y CI conservan el backend normal para
# no exigir collectstatic al ejecutar runserver o la suite.
if PRODUCTION:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': (
                'whitenoise.storage.'
                'CompressedManifestStaticFilesStorage'
            ),
        },
    }

# Archivos subidos por los usuarios (firmas, PDFs y evidencias).
# Local sigue usando filesystem. En Azure/UAT, si se activa el flag, se usa
# Blob Storage con Managed Identity mediante DefaultAzureCredential.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AZURE_MEDIA_ENABLED = env_bool(
    'DJANGO_AZURE_MEDIA_ENABLED',
    default=False,
)

if AZURE_MEDIA_ENABLED:
    azure_storage_account = os.environ.get(
        'DJANGO_AZURE_STORAGE_ACCOUNT',
        '',
    ).strip()
    azure_media_container = os.environ.get(
        'DJANGO_AZURE_MEDIA_CONTAINER',
        '',
    ).strip()

    missing_azure_media = []
    if not azure_storage_account:
        missing_azure_media.append('DJANGO_AZURE_STORAGE_ACCOUNT')
    if not azure_media_container:
        missing_azure_media.append('DJANGO_AZURE_MEDIA_CONTAINER')
    if missing_azure_media:
        raise ImproperlyConfigured(
            'Faltan variables de Azure Blob Storage: '
            + ', '.join(missing_azure_media)
        )

    from azure.identity import DefaultAzureCredential

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.azure_storage.AzureStorage',
            'OPTIONS': {
                'token_credential': DefaultAzureCredential(),
                'account_name': azure_storage_account,
                'azure_container': azure_media_container,
                'expiration_secs': env_int(
                    'DJANGO_AZURE_MEDIA_URL_EXPIRATION_SECS',
                    default=3600,
                ),
                'overwrite_files': False,
            },
        },
        'staticfiles': {
            'BACKEND': (
                'whitenoise.storage.'
                'CompressedManifestStaticFilesStorage'
                if PRODUCTION
                else 'django.contrib.staticfiles.storage.StaticFilesStorage'
            ),
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

# Redirecciones de autenticación
LOGIN_REDIRECT_URL = '/customers/search/'
LOGOUT_REDIRECT_URL = '/accounts/login/'


# API REST (canal del técnico)
# ---------------------------------------------------------------------
# La API queda cerrada por defecto: autenticación por token y permiso
# IsAuthenticated global. Cada endpoint abre o restringe explícitamente
# sobre esta base (el login se declara AllowAny; el canal técnico suma
# IsActiveTechnician). Ver docs/api_technician_auth.md.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}