# Generated by Django 5.2.17 on 2026-10-07 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingReviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_version', models.PositiveSmallIntegerField()),
                ('case_code', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de revisar'), ('REVIEWED', 'Revisado sin observaciones'), ('CHANGES', 'Falta dato o ajuste'), ('NOT_APPLICABLE', 'No aplica (explicar)')], max_length=20)),
                ('missing_data', models.CharField(blank=True, max_length=500)),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_review_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['reviewer', 'catalog_version', 'case_code'], name='review_user_version_case')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'REVIEWED', 'CHANGES', 'NOT_APPLICABLE'])), name='accounting_review_valid_status')],
            },
        ),
    ]
